// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.HBox hbox5;
    
    private Gtk.VBox vbox7;
    
    private Gtk.Frame frame2;
    
    private Gtk.Alignment GtkAlignment;
    
    private Gtk.Table table3;
    
    private Gtk.SpinButton altitude1;
    
    private Gtk.SpinButton attractors;
    
    private Gtk.SpinButton charge;
    
    private Gtk.SpinButton drag;
    
    private Gtk.Label label10;
    
    private Gtk.Label label11;
    
    private Gtk.Label label12;
    
    private Gtk.Label label7;
    
    private Gtk.Label label8;
    
    private Gtk.Label label9;
    
    private Gtk.SpinButton mass;
    
    private Gtk.SpinButton step;
    
    private Gtk.Label GtkLabel1;
    
    private Gtk.HButtonBox hbuttonbox2;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Button stop;
    
    private Gtk.Button clear1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Button simulateAll;
    
    private Gtk.ProgressBar progressbar2;
    
    private Gtk.EventBox eventBox;
    
    private Gtk.DrawingArea drawingArea;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Chaotic Pendulum");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.vbox7 = new Gtk.VBox();
        this.vbox7.Name = "vbox7";
        this.vbox7.Spacing = 6;
        // Container child vbox7.Gtk.Box+BoxChild
        this.frame2 = new Gtk.Frame();
        this.frame2.Name = "frame2";
        this.frame2.ShadowType = ((Gtk.ShadowType)(0));
        // Container child frame2.Gtk.Container+ContainerChild
        this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(12));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.table3 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
        this.table3.Name = "table3";
        this.table3.RowSpacing = ((uint)(6));
        this.table3.ColumnSpacing = ((uint)(6));
        // Container child table3.Gtk.Table+TableChild
        this.altitude1 = new Gtk.SpinButton(0.01, 10, 0.1);
        this.altitude1.CanFocus = true;
        this.altitude1.Name = "altitude1";
        this.altitude1.Adjustment.PageIncrement = 1;
        this.altitude1.ClimbRate = 1;
        this.altitude1.Digits = ((uint)(2));
        this.altitude1.Numeric = true;
        this.altitude1.Value = 0.2;
        this.table3.Add(this.altitude1);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table3[this.altitude1]));
        w1.TopAttach = ((uint)(3));
        w1.BottomAttach = ((uint)(4));
        w1.LeftAttach = ((uint)(1));
        w1.RightAttach = ((uint)(2));
        w1.XOptions = ((Gtk.AttachOptions)(4));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.attractors = new Gtk.SpinButton(1, 23, 1);
        this.attractors.CanFocus = true;
        this.attractors.Name = "attractors";
        this.attractors.Adjustment.PageIncrement = 5;
        this.attractors.ClimbRate = 1;
        this.attractors.Numeric = true;
        this.attractors.Value = 5;
        this.table3.Add(this.attractors);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table3[this.attractors]));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.charge = new Gtk.SpinButton(0, 10, 0.1);
        this.charge.CanFocus = true;
        this.charge.Name = "charge";
        this.charge.Adjustment.PageIncrement = 1;
        this.charge.ClimbRate = 1;
        this.charge.Digits = ((uint)(2));
        this.charge.Numeric = true;
        this.charge.Value = 1;
        this.table3.Add(this.charge);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table3[this.charge]));
        w3.TopAttach = ((uint)(1));
        w3.BottomAttach = ((uint)(2));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.drag = new Gtk.SpinButton(0, 10, 0.1);
        this.drag.CanFocus = true;
        this.drag.Name = "drag";
        this.drag.Adjustment.PageIncrement = 1;
        this.drag.ClimbRate = 1;
        this.drag.Digits = ((uint)(2));
        this.drag.Numeric = true;
        this.drag.Value = 0.5;
        this.table3.Add(this.drag);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table3[this.drag]));
        w4.TopAttach = ((uint)(4));
        w4.BottomAttach = ((uint)(5));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.Xalign = 0F;
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("Mass");
        this.table3.Add(this.label10);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table3[this.label10]));
        w5.TopAttach = ((uint)(2));
        w5.BottomAttach = ((uint)(3));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.Xalign = 0F;
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("Altitude");
        this.table3.Add(this.label11);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table3[this.label11]));
        w6.TopAttach = ((uint)(3));
        w6.BottomAttach = ((uint)(4));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label12 = new Gtk.Label();
        this.label12.Name = "label12";
        this.label12.Xalign = 0F;
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("Drag");
        this.table3.Add(this.label12);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table3[this.label12]));
        w7.TopAttach = ((uint)(4));
        w7.BottomAttach = ((uint)(5));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.Xalign = 0F;
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Attractors");
        this.table3.Add(this.label7);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table3[this.label7]));
        w8.XOptions = ((Gtk.AttachOptions)(4));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.Xalign = 0F;
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("Step");
        this.table3.Add(this.label8);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table3[this.label8]));
        w9.TopAttach = ((uint)(5));
        w9.BottomAttach = ((uint)(6));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.Xalign = 0F;
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("Charge");
        this.table3.Add(this.label9);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table3[this.label9]));
        w10.TopAttach = ((uint)(1));
        w10.BottomAttach = ((uint)(2));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.mass = new Gtk.SpinButton(0.01, 10, 0.1);
        this.mass.CanFocus = true;
        this.mass.Name = "mass";
        this.mass.Adjustment.PageIncrement = 1;
        this.mass.ClimbRate = 1;
        this.mass.Digits = ((uint)(2));
        this.mass.Numeric = true;
        this.mass.Value = 2;
        this.table3.Add(this.mass);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table3[this.mass]));
        w11.TopAttach = ((uint)(2));
        w11.BottomAttach = ((uint)(3));
        w11.LeftAttach = ((uint)(1));
        w11.RightAttach = ((uint)(2));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table3.Gtk.Table+TableChild
        this.step = new Gtk.SpinButton(0.01, 10, 0.01);
        this.step.CanFocus = true;
        this.step.Name = "step";
        this.step.Adjustment.PageIncrement = 0.1;
        this.step.ClimbRate = 1;
        this.step.Digits = ((uint)(2));
        this.step.Numeric = true;
        this.step.Value = 0.1;
        this.table3.Add(this.step);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table3[this.step]));
        w12.TopAttach = ((uint)(5));
        w12.BottomAttach = ((uint)(6));
        w12.LeftAttach = ((uint)(1));
        w12.RightAttach = ((uint)(2));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        this.GtkAlignment.Add(this.table3);
        this.frame2.Add(this.GtkAlignment);
        this.GtkLabel1 = new Gtk.Label();
        this.GtkLabel1.Name = "GtkLabel1";
        this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>Parameters</b>");
        this.GtkLabel1.UseMarkup = true;
        this.frame2.LabelWidget = this.GtkLabel1;
        this.vbox7.Add(this.frame2);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox7[this.frame2]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        w15.Padding = ((uint)(5));
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbuttonbox2 = new Gtk.HButtonBox();
        this.hbuttonbox2.Name = "hbuttonbox2";
        this.vbox7.Add(this.hbuttonbox2);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbuttonbox2]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Homogeneous = true;
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.stop = new Gtk.Button();
        this.stop.CanFocus = true;
        this.stop.Name = "stop";
        this.stop.UseUnderline = true;
        // Container child stop.Gtk.Container+ContainerChild
        Gtk.Alignment w17 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w18 = new Gtk.HBox();
        w18.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w19 = new Gtk.Image();
        w19.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-stop", Gtk.IconSize.Menu, 16);
        w18.Add(w19);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w21 = new Gtk.Label();
        w21.LabelProp = Mono.Unix.Catalog.GetString("Stop");
        w21.UseUnderline = true;
        w18.Add(w21);
        w17.Add(w18);
        this.stop.Add(w17);
        this.hbox3.Add(this.stop);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox3[this.stop]));
        w25.Position = 0;
        // Container child hbox3.Gtk.Box+BoxChild
        this.clear1 = new Gtk.Button();
        this.clear1.CanFocus = true;
        this.clear1.Name = "clear1";
        this.clear1.UseUnderline = true;
        // Container child clear1.Gtk.Container+ContainerChild
        Gtk.Alignment w26 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w27 = new Gtk.HBox();
        w27.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w28 = new Gtk.Image();
        w28.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-clear", Gtk.IconSize.Menu, 16);
        w27.Add(w28);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w30 = new Gtk.Label();
        w30.LabelProp = Mono.Unix.Catalog.GetString("Clear");
        w30.UseUnderline = true;
        w27.Add(w30);
        w26.Add(w27);
        this.clear1.Add(w26);
        this.hbox3.Add(this.clear1);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox3[this.clear1]));
        w34.Position = 1;
        this.vbox7.Add(this.hbox3);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
        w35.Position = 2;
        w35.Expand = false;
        w35.Fill = false;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.simulateAll = new Gtk.Button();
        this.simulateAll.CanFocus = true;
        this.simulateAll.Name = "simulateAll";
        this.simulateAll.UseUnderline = true;
        // Container child simulateAll.Gtk.Container+ContainerChild
        Gtk.Alignment w36 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w37 = new Gtk.HBox();
        w37.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w38 = new Gtk.Image();
        w38.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Menu, 16);
        w37.Add(w38);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w40 = new Gtk.Label();
        w40.LabelProp = Mono.Unix.Catalog.GetString("Simulate All");
        w40.UseUnderline = true;
        w37.Add(w40);
        w36.Add(w37);
        this.simulateAll.Add(w36);
        this.hbox2.Add(this.simulateAll);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox2[this.simulateAll]));
        w44.Position = 0;
        w44.Expand = false;
        w44.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.progressbar2 = new Gtk.ProgressBar();
        this.progressbar2.WidthRequest = 30;
        this.progressbar2.Name = "progressbar2";
        this.progressbar2.Text = "";
        this.hbox2.Add(this.progressbar2);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox2[this.progressbar2]));
        w45.Position = 1;
        this.vbox7.Add(this.hbox2);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox2]));
        w46.Position = 3;
        w46.Expand = false;
        w46.Fill = false;
        this.hbox5.Add(this.vbox7);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox5[this.vbox7]));
        w47.Position = 0;
        w47.Expand = false;
        w47.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.eventBox = new Gtk.EventBox();
        this.eventBox.Name = "eventBox";
        // Container child eventBox.Gtk.Container+ContainerChild
        this.drawingArea = new Gtk.DrawingArea();
        this.drawingArea.WidthRequest = 300;
        this.drawingArea.HeightRequest = 300;
        this.drawingArea.Name = "drawingArea";
        this.eventBox.Add(this.drawingArea);
        this.hbox5.Add(this.eventBox);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.hbox5[this.eventBox]));
        w49.Position = 1;
        this.Add(this.hbox5);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 456;
        this.DefaultHeight = 308;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.step.ValueChanged += new System.EventHandler(this.OnParameterValueChanged);
        this.mass.ValueChanged += new System.EventHandler(this.OnParameterValueChanged);
        this.drag.ValueChanged += new System.EventHandler(this.OnParameterValueChanged);
        this.charge.ValueChanged += new System.EventHandler(this.OnParameterValueChanged);
        this.attractors.ValueChanged += new System.EventHandler(this.OnAttractorsValueChanged);
        this.altitude1.ValueChanged += new System.EventHandler(this.OnParameterValueChanged);
        this.stop.Clicked += new System.EventHandler(this.OnStopClicked);
        this.clear1.Clicked += new System.EventHandler(this.OnClearClicked);
        this.eventBox.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.OnEventBoxButtonReleaseEvent);
        this.drawingArea.ExposeEvent += new Gtk.ExposeEventHandler(this.OnDrawingAreaExposeEvent);
        this.drawingArea.ConfigureEvent += new Gtk.ConfigureEventHandler(this.OnDrawingAreaConfigureEvent);
    }
}
